# Generated by Django 4.1.3 on 2023-05-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_ishome_alter_course_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
    ]
